/**
 * Tyros Group: request endpoint (Google Apps Script web app).
 * GENERATED by tools/make_apps_script.py from tools/forms.py. Do not edit the maps by hand.
 *
 * Receives the site forms, validates them on the server, records the lead in a Google Sheet,
 * notifies Tyros, and acknowledges the visitor (with the programme PDF attached for programme requests).
 *
 * Nothing sensitive is in the public JavaScript. Configuration lives in Script Properties:
 *   SHEET_ID              id of the Google Sheet that receives the leads            (required)
 *   NOTIFY_TO             internal recipient, default contact@tyros-group.com
 *   PDF_FILE_ID_DEFAULT   Drive file id of the programme PDF sent to visitors       (required for programme requests)
 *   PDF_FILE_ID_<id>      optional: a specific PDF per programme id (e.g. PDF_FILE_ID_dora-awareness)
 */
var PROGRAMMES = {"dora-awareness": "DORA Awareness", "ai-literacy": "AI Literacy & Responsible Use", "manager-recruiter": "Manager as Recruiter", "specialist-talent": "Hiring & Retaining Specialist Talent", "business-development": "Business Development in Financial Services", "client-relationships": "Strategic Client Relationships"};
var OFFERS = {"cro": ["Recruter un Chief Risk Officer", "Recruiting a Chief Risk Officer"], "cco": ["Recruter un Chief Compliance Officer", "Recruiting a Chief Compliance Officer"], "banking-insurance": ["Executive search banque & assurance", "Executive search for banking & insurance"], "actuarial": ["Executive search actuariat", "Executive search for actuarial roles"], "executive-search": ["Tyros Executive Search", "Tyros Executive Search"], "ai-act": ["AI Act & gouvernance de l'IA", "AI Act & AI governance"], "advisory": ["Tyros Advisory", "Tyros Advisory"], "boards": ["Conseils & dirigeants", "Boards & Executives"], "compliance": ["Conformité et avantage compétitif", "Compliance as a competitive advantage"], "membership-essential": ["Membership Essential", "Membership Essential"], "membership-professional": ["Membership Professional", "Membership Professional"], "membership-enterprise": ["Membership Enterprise", "Membership Enterprise"], "briefing": ["Briefing d'intelligence confidentiel", "Confidential intelligence briefing"], "private": ["Tyros Private", "Tyros Private"], "dora-awareness": ["DORA Awareness", "DORA Awareness"], "ai-literacy": ["AI Literacy & Responsible Use", "AI Literacy & Responsible Use"], "manager-recruiter": ["Manager as Recruiter", "Manager as Recruiter"], "specialist-talent": ["Hiring & Retaining Specialist Talent", "Hiring & Retaining Specialist Talent"], "business-development": ["Business Development in Financial Services", "Business Development in Financial Services"], "client-relationships": ["Strategic Client Relationships", "Strategic Client Relationships"]};
var TYPES = ['general', 'recruitment', 'consulting', 'academy'];
var LANGS = ['fr', 'en'];
var TIMING = ['urgent', '1-3', '3-6', 'open'];
var PARTICIPANTS = ['<10', '10-25', '25-50', '50+', 'tbd'];
var FORMATS = ['remote', 'in-person', 'discuss'];
var INTENTS = ['', 'programme', 'session'];
var MIN_FILL_MS = 4000;                 // faster than this: not a human
var MAX_FILL_MS = 24 * 3600 * 1000;     // older than a day: stale form
var MAX_PER_EMAIL_PER_HOUR = 3;
var MAX_PER_HOUR = 120;
var HEADERS = ['Reference', 'Received (UTC)', 'Type', 'Language', 'Offer / programme', 'Intent', 'Name', 'Company', 'Email',
  'Role / profile', 'Location', 'Timing', 'Topic / need', 'Deadline', 'Participants', 'Format', 'Period', 'Message',
  'Source page', 'Source URL', 'Status', 'Acknowledgement', 'Programme PDF'];

var L = {
  fr: { types: { general: 'Contact général', recruitment: 'Recrutement', consulting: 'Conseil', academy: 'Tyros Academy' },
    subject: 'Tyros Group : nous avons bien reçu votre demande', subjectProg: 'Tyros Group : votre programme',
    hello: 'Bonjour', body: 'Nous avons bien reçu votre demande et nous vous répondons sous 48 heures ouvrées.',
    bodyProg: 'Vous trouverez le programme en pièce jointe. Nous revenons vers vous sous 48 heures ouvrées.',
    ctx: 'Votre demande concerne', ref: 'Référence', sign: 'Cordialement,', team: 'Tyros Group',
    conf: 'Votre demande est traitée en toute confidentialité.' },
  en: { types: { general: 'General enquiry', recruitment: 'Recruitment', consulting: 'Consulting', academy: 'Tyros Academy' },
    subject: 'Tyros Group: we have received your request', subjectProg: 'Tyros Group: your programme',
    hello: 'Hello', body: 'We have received your request and will reply within 48 working hours.',
    bodyProg: 'Please find the programme attached. We will come back to you within 48 working hours.',
    ctx: 'Your request concerns', ref: 'Reference', sign: 'Kind regards,', team: 'Tyros Group',
    conf: 'Your request is handled in full confidence.' }
};

function doGet() { return json_({ ok: true, service: 'tyros-requests' }); }

function doPost(e) {
  try {
    var p = (e && e.parameter) || {};
    // 1. honeypot: pretend success, store nothing
    if (clean_(p.website, 200)) return json_({ ok: true, ref: '' });
    // 2. minimum / maximum fill time
    var t0 = parseInt(p.t0, 10), now = Date.now();
    if (!t0 || now - t0 < MIN_FILL_MS || now - t0 > MAX_FILL_MS) return json_({ ok: false, error: 'timing' });
    // 3. validate
    var r = validate_(p);
    if (!r.ok) return json_({ ok: false, error: r.error });
    var v = r.v;
    // 4. rate limit
    if (!rateOk_(v.email)) return json_({ ok: false, error: 'rate' });
    // 5. record (locked), then notify and acknowledge
    var ref = reference_();
    var received = new Date();
    var ack = { status: 'pending', pdf: '' };
    var row = appendLead_(ref, received, v, ack);        // writes the row, returns row index
    ack = acknowledge_(ref, v, ack);                     // sends the visitor acknowledgement (+ PDF)
    notify_(ref, received, v, ack);                      // internal notification
    updateAck_(row, ack);
    return json_({ ok: true, ref: ref });
  } catch (err) {
    console.error(err && err.stack || err);
    return json_({ ok: false, error: 'server' });
  }
}

function validate_(p) {
  var v = {
    type: clean_(p.type, 20), lang: clean_(p.lang, 4), offer: clean_(p.offer, 40), intent: clean_(p.intent, 12),
    name: clean_(p.name, 120), company: clean_(p.company, 160), email: clean_(p.email, 200).toLowerCase(),
    role: clean_(p.role, 200), location: clean_(p.location, 160), timing: clean_(p.timing, 12),
    topic: clean_(p.topic, 300), deadline: clean_(p.deadline, 120), programme: clean_(p.programme, 40),
    participants: clean_(p.participants, 12), format: clean_(p.format, 12), period: clean_(p.period, 120),
    message: clean_(p.message, 5000, true), page: clean_(p.page, 160), source_url: clean_(p.source_url, 300)
  };
  if (TYPES.indexOf(v.type) < 0 || LANGS.indexOf(v.lang) < 0) return { ok: false, error: 'invalid' };
  if (INTENTS.indexOf(v.intent) < 0) v.intent = '';
  if (v.offer && !OFFERS[v.offer]) v.offer = '';
  if (!v.name || !v.company || !v.email) return { ok: false, error: 'required' };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v.email)) return { ok: false, error: 'email' };
  if (v.type === 'recruitment' && (!v.role || !v.location || TIMING.indexOf(v.timing) < 0)) return { ok: false, error: 'required' };
  if (v.type === 'consulting' && !v.topic) return { ok: false, error: 'required' };
  if (v.type === 'general' && !v.message) return { ok: false, error: 'required' };
  if (v.type === 'academy') {
    var okProg = v.programme === 'multiple' || PROGRAMMES[v.programme];
    if (!okProg || PARTICIPANTS.indexOf(v.participants) < 0 || FORMATS.indexOf(v.format) < 0) return { ok: false, error: 'required' };
    if (!v.offer && PROGRAMMES[v.programme]) v.offer = v.programme;
  }
  // keep only the fields that belong to the journey
  if (v.type !== 'recruitment') { v.role = ''; v.location = ''; v.timing = ''; }
  if (v.type !== 'consulting') { v.topic = ''; v.deadline = ''; }
  if (v.type !== 'academy') { v.programme = ''; v.participants = ''; v.format = ''; v.period = ''; v.intent = ''; }
  return { ok: true, v: v };
}

function clean_(s, max, keepNewlines) {
  s = String(s == null ? '' : s);
  s = s.replace(keepNewlines ? /[\u0000-\u0009\u000B\u000C\u000E-\u001F\u007F]/g : /[\u0000-\u001F\u007F]/g, ' ');
  return s.trim().slice(0, max);
}
function cell_(s) { s = String(s || ''); return /^[=+\-@]/.test(s) ? "'" + s : s; }   // no formula injection in the Sheet

function rateOk_(email) {
  var cache = CacheService.getScriptCache();
  var hour = Math.floor(Date.now() / 3600000);
  var k1 = 'e:' + hour + ':' + Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, email)).slice(0, 20);
  var k2 = 'all:' + hour;
  var n1 = parseInt(cache.get(k1) || '0', 10), n2 = parseInt(cache.get(k2) || '0', 10);
  if (n1 >= MAX_PER_EMAIL_PER_HOUR || n2 >= MAX_PER_HOUR) return false;
  cache.put(k1, String(n1 + 1), 3700); cache.put(k2, String(n2 + 1), 3700);
  return true;
}

function reference_() {
  var d = Utilities.formatDate(new Date(), 'UTC', 'yyyyMMdd');
  var rnd = Math.floor(Math.random() * 46656).toString(36).toUpperCase();
  while (rnd.length < 3) rnd = '0' + rnd;
  return 'TY-' + d + '-' + rnd;
}

function sheet_() {
  var id = PropertiesService.getScriptProperties().getProperty('SHEET_ID');
  if (!id) throw new Error('SHEET_ID is not set');
  var ss = SpreadsheetApp.openById(id);
  var sh = ss.getSheetByName('Leads');
  if (!sh) {
    sh = ss.insertSheet('Leads');
    sh.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS]).setFontWeight('bold').setBackground('#050E1D').setFontColor('#F4EFE4');
    sh.setFrozenRows(1);
  }
  return sh;
}

function appendLead_(ref, received, v, ack) {
  var lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try {
    var sh = sheet_();
    var offerLabel = v.offer ? (OFFERS[v.offer][v.lang === 'en' ? 1 : 0]) : (v.programme === 'multiple' ? 'Multiple programmes' : '');
    var row = [ref, Utilities.formatDate(received, 'UTC', "yyyy-MM-dd'T'HH:mm:ss'Z'"), v.type, v.lang, offerLabel, v.intent,
      v.name, v.company, v.email, v.role, v.location, v.timing, v.topic, v.deadline, v.participants, v.format, v.period, v.message,
      v.page, v.source_url, 'New', ack.status, ack.pdf].map(cell_);
    sh.appendRow(row);
    return sh.getLastRow();
  } finally { lock.releaseLock(); }
}
function updateAck_(row, ack) {
  var sh = sheet_();
  sh.getRange(row, 22, 1, 2).setValues([[ack.status, ack.pdf]]);
}

function pdfFor_(v) {
  var props = PropertiesService.getScriptProperties();
  var id = (v.programme && props.getProperty('PDF_FILE_ID_' + v.programme)) || (v.offer && props.getProperty('PDF_FILE_ID_' + v.offer)) || props.getProperty('PDF_FILE_ID_DEFAULT');
  return id ? DriveApp.getFileById(id).getBlob() : null;
}

function acknowledge_(ref, v, ack) {
  var t = L[v.lang];
  var wantsPdf = v.type === 'academy' && v.intent === 'programme';
  var offerLabel = v.offer ? OFFERS[v.offer][v.lang === 'en' ? 1 : 0] : '';
  var lines = [t.hello + ' ' + v.name + ',', '', wantsPdf ? t.bodyProg : t.body];
  if (offerLabel) lines.push('', t.ctx + ' : ' + offerLabel);
  lines.push('', t.ref + ' : ' + ref, '', t.conf, '', t.sign, t.team);
  var text = lines.join('\n');
  var html = '<div style="font-family:Arial,sans-serif;font-size:15px;line-height:1.55;color:#050E1D">' +
    '<p>' + esc_(t.hello) + ' ' + esc_(v.name) + ',</p><p>' + esc_(wantsPdf ? t.bodyProg : t.body) + '</p>' +
    (offerLabel ? '<p>' + esc_(t.ctx) + ' : <strong>' + esc_(offerLabel) + '</strong></p>' : '') +
    '<p style="color:#5b6779">' + esc_(t.ref) + ' : ' + esc_(ref) + '<br>' + esc_(t.conf) + '</p>' +
    '<p>' + esc_(t.sign) + '<br><strong>' + esc_(t.team) + '</strong></p></div>';
  var opts = { name: 'Tyros Group', htmlBody: html, replyTo: notifyTo_() };
  var pdfStatus = '';
  if (wantsPdf) {
    var blob = null;
    try { blob = pdfFor_(v); } catch (e) { console.error(e); }
    if (blob) { opts.attachments = [blob.setName('Tyros-Academy-' + (v.lang === 'en' ? 'programme' : 'programme') + '.pdf')]; pdfStatus = 'attached'; }
    else pdfStatus = 'MISSING';
  }
  try {
    MailApp.sendEmail(v.email, wantsPdf ? t.subjectProg : t.subject, text, opts);
    return { status: 'sent', pdf: pdfStatus };
  } catch (e) { console.error(e); return { status: 'FAILED', pdf: pdfStatus }; }
}

function notifyTo_() { return PropertiesService.getScriptProperties().getProperty('NOTIFY_TO') || 'contact@tyros-group.com'; }

function notify_(ref, received, v, ack) {
  var tl = L.fr.types[v.type];
  var offerLabel = v.offer ? OFFERS[v.offer][0] : (v.programme === 'multiple' ? 'Plusieurs programmes' : '');
  var rows = [['Référence', ref], ['Reçu (UTC)', Utilities.formatDate(received, 'UTC', "yyyy-MM-dd HH:mm")], ['Type', tl], ['Langue', v.lang.toUpperCase()],
    ['Offre / programme', offerLabel], ['Intention', v.intent], ['Nom', v.name], ['Entreprise', v.company], ['Email', v.email],
    ['Poste / profil', v.role], ['Localisation', v.location], ['Calendrier', v.timing], ['Sujet / besoin', v.topic], ['Échéance', v.deadline],
    ['Participants', v.participants], ['Format', v.format], ['Période', v.period], ['Page d\'origine', v.page], ['URL', v.source_url],
    ['Accusé de réception', ack.status], ['PDF programme', ack.pdf]].filter(function (r) { return r[1]; });
  var text = rows.map(function (r) { return r[0] + ' : ' + r[1]; }).join('\n') + '\n\nMessage :\n' + (v.message || '(aucun)');
  var warn = (ack.pdf === 'MISSING' ? '\n\n/!\\ Le PDF du programme n\'a pas pu être joint : configurer PDF_FILE_ID_DEFAULT.' : '') + (ack.status === 'FAILED' ? '\n\n/!\\ L\'accusé de réception n\'a pas pu être envoyé.' : '');
  MailApp.sendEmail({ to: notifyTo_(), replyTo: v.email, name: 'Tyros Group (site)',
    subject: '[Tyros] ' + tl + (offerLabel ? ' · ' + offerLabel : '') + ' · ' + v.company + ' (' + v.lang.toUpperCase() + ') ' + ref,
    body: text + warn });
}

function esc_(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function json_(o) { return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON); }

/** Run once from the editor to grant the Sheets, Mail and Drive permissions, and create the Leads tab. */
function authorizeOnce() {
  sheet_();
  var id = PropertiesService.getScriptProperties().getProperty('PDF_FILE_ID_DEFAULT');
  if (id) DriveApp.getFileById(id).getName();
  MailApp.getRemainingDailyQuota();
  console.log('OK: permissions granted, Leads sheet ready.');
}
