/**
 * Tyros Group: request endpoint (Google Apps Script web app).
 * GENERATED by tools/make_apps_script.py from tools/forms.py. Do not edit the maps by hand.
 *
 * Receives the site forms, validates them on the server, records the lead in a Google Sheet,
 * notifies Tyros, and sends the visitor a plain acknowledgement of receipt. No document is ever sent automatically:
 * a programme request is identified by Tyros first, then answered by hand.
 *
 * Nothing sensitive is in the public JavaScript. Configuration lives in Script Properties:
 *   SHEET_ID              id of the Google Sheet that receives the leads            (required)
 *   NOTIFY_TO             internal recipient, default contact@tyros-group.com
 */
var PROGRAMMES = {"dora-awareness": "DORA Awareness", "ai-literacy": "AI Literacy & Responsible Use", "manager-recruiter": "Manager as Recruiter", "specialist-talent": "Hiring & Retaining Specialist Talent", "business-development": "Business Development in Financial Services", "client-relationships": "Strategic Client Relationships"};
var OFFERS = {"cro": ["Recruter un Chief Risk Officer", "Recruiting a Chief Risk Officer"], "cco": ["Recruter un Chief Compliance Officer", "Recruiting a Chief Compliance Officer"], "banking-insurance": ["Executive search banque & assurance", "Executive search for banking & insurance"], "actuarial": ["Executive search actuariat", "Executive search for actuarial roles"], "executive-search": ["Tyros Executive Search", "Tyros Executive Search"], "ai-act": ["AI Act & gouvernance de l'IA", "AI Act & AI governance"], "advisory": ["Tyros Advisory", "Tyros Advisory"], "boards": ["Conseils & dirigeants", "Boards & Executives"], "compliance": ["Conformité et avantage compétitif", "Compliance as a competitive advantage"], "membership-essential": ["Membership Essential", "Membership Essential"], "membership-professional": ["Membership Professional", "Membership Professional"], "membership-enterprise": ["Membership Enterprise", "Membership Enterprise"], "briefing": ["Briefing d'intelligence confidentiel", "Confidential intelligence briefing"], "private": ["Tyros Private", "Tyros Private"], "dora-awareness": ["DORA Awareness", "DORA Awareness"], "ai-literacy": ["AI Literacy & Responsible Use", "AI Literacy & Responsible Use"], "manager-recruiter": ["Manager as Recruiter", "Manager as Recruiter"], "specialist-talent": ["Hiring & Retaining Specialist Talent", "Hiring & Retaining Specialist Talent"], "business-development": ["Business Development in Financial Services", "Business Development in Financial Services"], "client-relationships": ["Strategic Client Relationships", "Strategic Client Relationships"]};
var TYPES = ['general', 'recruitment', 'consulting', 'academy'];
var LANGS = ['fr', 'en'];
var TIMING = ['urgent', '1-3', '3-6', 'open'];
var PARTICIPANTS = ['<10', '10-25', '25-50', '50+', 'tbd'];
var FORMATS = ['remote', 'in-person', 'discuss'];
var INTENTS = ['', 'programme', 'session'];
var MIN_FILL_MS = 4000;                 // faster than this: not a human
var MAX_FILL_MS = 24 * 3600 * 1000;     // older than a day: stale form
var MAX_PER_EMAIL_PER_HOUR = 3;
var MAX_PER_HOUR = 120;
var HEADERS = ['Reference', 'Received (UTC)', 'Type', 'Language', 'Offer / programme', 'Intent', 'Name', 'Company', 'Email',
  'Role / profile', 'Location', 'Timing', 'Topic / need', 'Deadline', 'Participants', 'Format', 'Period', 'Message',
  'Source page', 'Source URL', 'Status', 'Acknowledgement', 'Programme sent (manual)'];

var L = {
  fr: { types: { general: 'Contact général', recruitment: 'Recrutement', consulting: 'Conseil', academy: 'Tyros Academy' },
    subject: 'Tyros Group : nous avons bien reçu votre demande',
    hello: 'Bonjour', body: 'Nous avons bien reçu votre demande et nous vous répondons sous 48 heures ouvrées.',
    ctx: 'Votre demande concerne', ref: 'Référence', sign: 'Cordialement,', team: 'Tyros Group',
    conf: 'Votre demande est traitée en toute confidentialité.' },
  en: { types: { general: 'General enquiry', recruitment: 'Recruitment', consulting: 'Consulting', academy: 'Tyros Academy' },
    subject: 'Tyros Group: we have received your request',
    hello: 'Hello', body: 'We have received your request and will reply within 48 working hours.',
    ctx: 'Your request concerns', ref: 'Reference', sign: 'Kind regards,', team: 'Tyros Group',
    conf: 'Your request is handled in full confidence.' }
};

function doGet() { return json_({ ok: true, service: 'tyros-requests' }); }

function doPost(e) {
  try {
    var p = (e && e.parameter) || {};
    // 1. honeypot: pretend success, store nothing
    if (clean_(p.website, 200)) return json_({ ok: true, ref: '' });
    // 2. minimum / maximum fill time
    var t0 = parseInt(p.t0, 10), now = Date.now();
    if (!t0 || now - t0 < MIN_FILL_MS || now - t0 > MAX_FILL_MS) return json_({ ok: false, error: 'timing' });
    // 3. validate
    var r = validate_(p);
    if (!r.ok) return json_({ ok: false, error: r.error });
    var v = r.v;
    // 4. rate limit
    if (!rateOk_(v.email)) return json_({ ok: false, error: 'rate' });
    // 5. record (locked), then notify and acknowledge
    var ref = reference_();
    var received = new Date();
    var ack = { status: 'pending' };
    var row = appendLead_(ref, received, v, ack);        // writes the row, returns row index
    ack = acknowledge_(ref, v, ack);                     // sends the visitor a plain acknowledgement of receipt
    notify_(ref, received, v, ack);                      // internal notification
    updateAck_(row, ack);
    return json_({ ok: true, ref: ref });
  } catch (err) {
    console.error(err && err.stack || err);
    return json_({ ok: false, error: 'server' });
  }
}

function validate_(p) {
  var v = {
    type: clean_(p.type, 20), lang: clean_(p.lang, 4), offer: clean_(p.offer, 40), intent: clean_(p.intent, 12),
    name: clean_(p.name, 120), company: clean_(p.company, 160), email: clean_(p.email, 200).toLowerCase(),
    role: clean_(p.role, 200), location: clean_(p.location, 160), timing: clean_(p.timing, 12),
    topic: clean_(p.topic, 300), deadline: clean_(p.deadline, 120), programme: clean_(p.programme, 40),
    participants: clean_(p.participants, 12), format: clean_(p.format, 12), period: clean_(p.period, 120),
    message: clean_(p.message, 5000, true), page: clean_(p.page, 160), source_url: clean_(p.source_url, 300)
  };
  if (TYPES.indexOf(v.type) < 0 || LANGS.indexOf(v.lang) < 0) return { ok: false, error: 'invalid' };
  if (INTENTS.indexOf(v.intent) < 0) v.intent = '';
  if (v.offer && !OFFERS[v.offer]) v.offer = '';
  if (!v.name || !v.company || !v.email) return { ok: false, error: 'required' };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v.email)) return { ok: false, error: 'email' };
  if (v.type === 'recruitment' && (!v.role || !v.location || TIMING.indexOf(v.timing) < 0)) return { ok: false, error: 'required' };
  if (v.type === 'consulting' && !v.topic) return { ok: false, error: 'required' };
  if (v.type === 'general' && !v.message) return { ok: false, error: 'required' };
  if (v.type === 'academy') {
    var okProg = v.programme === 'multiple' || PROGRAMMES[v.programme];
    if (!okProg || PARTICIPANTS.indexOf(v.participants) < 0 || FORMATS.indexOf(v.format) < 0) return { ok: false, error: 'required' };
    if (!v.offer && PROGRAMMES[v.programme]) v.offer = v.programme;
  }
  // keep only the fields that belong to the journey
  if (v.type !== 'recruitment') { v.role = ''; v.location = ''; v.timing = ''; }
  if (v.type !== 'consulting') { v.topic = ''; v.deadline = ''; }
  if (v.type !== 'academy') { v.programme = ''; v.participants = ''; v.format = ''; v.period = ''; v.intent = ''; }
  return { ok: true, v: v };
}

function clean_(s, max, keepNewlines) {
  s = String(s == null ? '' : s);
  s = s.replace(keepNewlines ? /[\u0000-\u0009\u000B\u000C\u000E-\u001F\u007F]/g : /[\u0000-\u001F\u007F]/g, ' ');
  return s.trim().slice(0, max);
}
function cell_(s) { s = String(s || ''); return /^[=+\-@]/.test(s) ? "'" + s : s; }   // no formula injection in the Sheet

function rateOk_(email) {
  var cache = CacheService.getScriptCache();
  var hour = Math.floor(Date.now() / 3600000);
  var k1 = 'e:' + hour + ':' + Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, email)).slice(0, 20);
  var k2 = 'all:' + hour;
  var n1 = parseInt(cache.get(k1) || '0', 10), n2 = parseInt(cache.get(k2) || '0', 10);
  if (n1 >= MAX_PER_EMAIL_PER_HOUR || n2 >= MAX_PER_HOUR) return false;
  cache.put(k1, String(n1 + 1), 3700); cache.put(k2, String(n2 + 1), 3700);
  return true;
}

function reference_() {
  var d = Utilities.formatDate(new Date(), 'UTC', 'yyyyMMdd');
  var rnd = Math.floor(Math.random() * 46656).toString(36).toUpperCase();
  while (rnd.length < 3) rnd = '0' + rnd;
  return 'TY-' + d + '-' + rnd;
}

function sheet_() {
  var id = PropertiesService.getScriptProperties().getProperty('SHEET_ID');
  if (!id) throw new Error('SHEET_ID is not set');
  var ss = SpreadsheetApp.openById(id);
  var sh = ss.getSheetByName('Leads');
  if (!sh) {
    sh = ss.insertSheet('Leads');
    sh.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS]).setFontWeight('bold').setBackground('#050E1D').setFontColor('#F4EFE4');
    sh.setFrozenRows(1);
  }
  return sh;
}

function appendLead_(ref, received, v, ack) {
  var lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try {
    var sh = sheet_();
    var offerLabel = v.offer ? (OFFERS[v.offer][v.lang === 'en' ? 1 : 0]) : (v.programme === 'multiple' ? 'Multiple programmes' : '');
    var row = [ref, Utilities.formatDate(received, 'UTC', "yyyy-MM-dd'T'HH:mm:ss'Z'"), v.type, v.lang, offerLabel, v.intent,
      v.name, v.company, v.email, v.role, v.location, v.timing, v.topic, v.deadline, v.participants, v.format, v.period, v.message,
      v.page, v.source_url, 'New', ack.status, ''].map(cell_);
    sh.appendRow(row);
    return sh.getLastRow();
  } finally { lock.releaseLock(); }
}
function updateAck_(row, ack) {
  var sh = sheet_();
  sh.getRange(row, 22, 1, 1).setValues([[ack.status]]);
}

function acknowledge_(ref, v, ack) {
  var t = L[v.lang];
  var offerLabel = v.offer ? OFFERS[v.offer][v.lang === 'en' ? 1 : 0] : '';
  var lines = [t.hello + ' ' + v.name + ',', '', t.body];
  if (offerLabel) lines.push('', t.ctx + ' : ' + offerLabel);
  lines.push('', t.ref + ' : ' + ref, '', t.conf, '', t.sign, t.team);
  var text = lines.join('\n');
  var html = '<div style="font-family:Arial,sans-serif;font-size:15px;line-height:1.55;color:#050E1D">' +
    '<p>' + esc_(t.hello) + ' ' + esc_(v.name) + ',</p><p>' + esc_(t.body) + '</p>' +
    (offerLabel ? '<p>' + esc_(t.ctx) + ' : <strong>' + esc_(offerLabel) + '</strong></p>' : '') +
    '<p style="color:#5b6779">' + esc_(t.ref) + ' : ' + esc_(ref) + '<br>' + esc_(t.conf) + '</p>' +
    '<p>' + esc_(t.sign) + '<br><strong>' + esc_(t.team) + '</strong></p></div>';
  try {
    MailApp.sendEmail(v.email, t.subject, text, { name: 'Tyros Group', htmlBody: html, replyTo: notifyTo_() });
    return { status: 'sent' };
  } catch (e) { console.error(e); return { status: 'FAILED' }; }
}

function notifyTo_() { return PropertiesService.getScriptProperties().getProperty('NOTIFY_TO') || 'contact@tyros-group.com'; }

function notify_(ref, received, v, ack) {
  var tl = L.fr.types[v.type];
  var offerLabel = v.offer ? OFFERS[v.offer][0] : (v.programme === 'multiple' ? 'Plusieurs programmes' : '');
  var rows = [['Référence', ref], ['Reçu (UTC)', Utilities.formatDate(received, 'UTC', "yyyy-MM-dd HH:mm")], ['Type', tl], ['Langue', v.lang.toUpperCase()],
    ['Offre / programme', offerLabel], ['Intention', v.intent], ['Nom', v.name], ['Entreprise', v.company], ['Email', v.email],
    ['Poste / profil', v.role], ['Localisation', v.location], ['Calendrier', v.timing], ['Sujet / besoin', v.topic], ['Échéance', v.deadline],
    ['Participants', v.participants], ['Format', v.format], ['Période', v.period], ['Page d\'origine', v.page], ['URL', v.source_url],
    ['Accusé de réception', ack.status]].filter(function (r) { return r[1]; });
  var text = rows.map(function (r) { return r[0] + ' : ' + r[1]; }).join('\n') + '\n\nMessage :\n' + (v.message || '(aucun)');
  var todo = (v.type === 'academy' && v.intent === 'programme') ? '\n\n>>> DEMANDE DE PROGRAMME : identifier la personne, puis envoyer le programme manuellement (aucun document n\'a été envoyé automatiquement). Noter l\'envoi dans la colonne "Programme sent (manual)" de la Sheet.' : '';
  var warn = todo + (ack.status === 'FAILED' ? '\n\n/!\\ L\'accusé de réception n\'a pas pu être envoyé.' : '');
  MailApp.sendEmail({ to: notifyTo_(), replyTo: v.email, name: 'Tyros Group (site)',
    subject: '[Tyros] ' + tl + (offerLabel ? ' · ' + offerLabel : '') + ' · ' + v.company + ' (' + v.lang.toUpperCase() + ') ' + ref,
    body: text + warn });
}

function esc_(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function json_(o) { return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON); }

/** Run once from the editor to grant the Sheets and Mail permissions, and create the Leads tab. */
function authorizeOnce() {
  sheet_();
  MailApp.getRemainingDailyQuota();
  console.log('OK: permissions granted, Leads sheet ready.');
}

/**
 * Real end-to-end test, run from the Apps Script editor (Run > selfTest) AFTER deployment.
 * Sends one request per journey through the live web app, to the address of the person running it,
 * then reports what landed in the Sheet. Test rows are marked "[TEST]" in the Company column.
 */
function selfTest() {
  var url = ScriptApp.getService().getUrl();
  if (!url) throw new Error('Deploy the web app first (Deploy > New deployment > Web app).');
  var me = Session.getActiveUser().getEmail() || notifyTo_();
  var t0 = String(Date.now() - 10000);
  var base = { name: 'Test Tyros', company: '[TEST]', email: me, lang: 'fr', page: '/selftest', source_url: 'selftest', t0: t0 };
  var cases = [
    { type: 'general', message: 'Test contact général' },
    { type: 'recruitment', offer: 'cro', role: 'Chief Risk Officer', location: 'Paris', timing: '1-3', message: 'Test recrutement' },
    { type: 'consulting', offer: 'ai-act', topic: 'AI Act', deadline: 'T1', message: 'Test conseil' },
    { type: 'academy', offer: 'manager-recruiter', intent: 'programme', programme: 'manager-recruiter', participants: '10-25', format: 'remote', period: 'T2', message: 'Test programme' },
    { type: 'academy', offer: 'dora-awareness', intent: 'session', programme: 'dora-awareness', participants: '25-50', format: 'discuss', lang: 'en', message: 'Test session' }
  ];
  var out = [];
  cases.forEach(function (c, i) {
    var payload = {}; Object.keys(base).forEach(function (k) { payload[k] = base[k]; }); Object.keys(c).forEach(function (k) { payload[k] = c[k]; });
    var r = UrlFetchApp.fetch(url, { method: 'post', payload: payload, muteHttpExceptions: true, followRedirects: true });
    out.push((i + 1) + '. ' + c.type + (c.intent ? '/' + c.intent : '') + ' -> ' + r.getResponseCode() + ' ' + r.getContentText());
    Utilities.sleep(1500);
  });
  // honeypot and too-fast checks must be silent / rejected
  var hp = UrlFetchApp.fetch(url, { method: 'post', payload: { type: 'general', lang: 'fr', name: 'x', company: 'x', email: me, message: 'x', website: 'spam', t0: t0 }, muteHttpExceptions: true }).getContentText();
  var fast = UrlFetchApp.fetch(url, { method: 'post', payload: { type: 'general', lang: 'fr', name: 'x', company: 'x', email: me, message: 'x', t0: String(Date.now()) }, muteHttpExceptions: true }).getContentText();
  out.push('honeypot -> ' + hp + ' (expect ok:true, nothing stored)');
  out.push('too fast -> ' + fast + ' (expect error:timing)');
  var sh = sheet_(), last = sh.getLastRow();
  out.push('Sheet rows now: ' + last + ' (check the 5 [TEST] rows, with offer, intent, language, source page)');
  out.push('Mails: 5 acknowledgements to ' + me + ' and 5 internal notifications to ' + notifyTo_() + ' (the 5 acknowledgements carry no attachment).');
  console.log(out.join('\n'));
}
